# Generated by Django 2.1.2 on 2018-11-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_make_user_game_combination_unique_in_player'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ship',
            unique_together={('player', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='turn',
            unique_together={('player', 'number')},
        ),
    ]
