# Generated by Django 2.1.2 on 2018-11-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_unique_ship_types_and_turn_numbers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turn',
            unique_together={('player', 'number'), ('player', 'x', 'y')},
        ),
    ]
