# Generated by Django 2.1.2 on 2018-11-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_add_validators_to_x_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='starting_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_player_games', to='game.Player', verbose_name='Starting player'),
        ),
    ]
