# Generated by Django 2.1.2 on 2018-12-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_starting_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='allow_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='draw',
            field=models.BooleanField(default=False),
        ),
    ]
